### ISSUE TITLE
Remove External http Access

### ISSUE THREAD

**Issue by benofben** [DSPN/google-cloud-platform-dse#7]
GCP seems to have a feature where websites can be accessed from within the console.  This would lock down access to OpsCenter, removing potential security issues.  Perhaps we should do this instead of setting up firewall rules.

I'm encountering an issue when I try to use this feature, but in principle it looks great.  Will discuss with google on our next call.

**Comment by vfgomes** [comment]
Yeah, that feature you encoutered about opening SSH on a different port is not doing port forwarding, but rather trying to listen for ssh on a different port.

**Comment by benofben** [comment]
Ah.  Ok.  Nevermind this idea then.
